[Assets]
next_asset_id = 5

    [[Assets.Geometries]]
    asset_id = 3
    name = 'FullscreenQuad'
    type = 'ScreenQuadGeometry'

    [[Assets.Graphs]]
    asset_id = 4
    edges = [
        { edge_id = 4, from_node = 2, to_node = 4 },
        { edge_id = 6, from_node = 3, to_node = 13 },
        { edge_id = 7, from_node = 2, to_node = 11 },
        { edge_id = 8, from_node = 14, to_node = 12 },
        { edge_id = 10, from_node = 25, to_node = 23 },
        { edge_id = 11, from_node = 25, to_node = 24 },
        { edge_id = 12, from_node = 27, to_node = 7 },
        { edge_id = 13, from_node = 26, to_node = 17 },
        { edge_id = 14, from_node = 10, to_node = 18 },
        { edge_id = 15, from_node = 15, to_node = 22 },
        { edge_id = 16, from_node = 2, to_node = 20 },
        { edge_id = 17, from_node = 2, to_node = 16 },
        { edge_id = 19, from_node = 28, to_node = 21 },
        { edge_id = 22, from_node = 31, to_node = 29 },
        { edge_id = 23, from_node = 31, to_node = 30 },
        { edge_id = 25, from_node = 2, to_node = 33 },
        { edge_id = 27, from_node = 19, to_node = 35 },
        { edge_id = 29, from_node = 32, to_node = 40 },
        { edge_id = 30, from_node = 37, to_node = 0 },
        { edge_id = 31, from_node = 2, to_node = 38 },
        { edge_id = 34, from_node = 9, to_node = 42 },
        { edge_id = 35, from_node = 43, to_node = 41 },
        { edge_id = 36, from_node = 43, to_node = 36 },
        { edge_id = 37, from_node = 44, to_node = 39 },
        { edge_id = 38, from_node = 45, to_node = 34 }
    ]
    geometry_id = 3
    name = 'Default Graph'
    next_edge_id = 39
    next_node_id = 20
    next_pin_id = 46
    nodes = [
        { input_pin = 0, node_id = 0, out_texture = 12, position = { x = 1609.0, y = 281.0 }, type = 'OutputNode' },
        { node_id = 2, output_pin = 2, position = { x = -614.860595703125, y = -116.08485412597656 }, type = 'ViewportNode' },
        { node_id = 3, output_pin = 3, position = { x = -198.00001525878906, y = 399.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 4, type = 5 },
            { identifier = 'u_mode', pin_id = 7, type = 4 },
            { identifier = 'rangeMult', pin_id = 29, type = 4 },
            { identifier = 'u_cat', pin_id = 42, type = 8 }
        ] },
        { node_id = 5, output_pin = 9, position = { x = -617.0, y = 165.00003051757812 }, texture_id = 2, type = 'Texture2DNode' },
        { node_id = 6, output_pin = 10, position = { x = 105.99998474121094, y = 401.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 11, type = 5 },
            { identifier = 'u_mode', pin_id = 12, type = 4 },
            { identifier = 'u_cat', pin_id = 13, type = 8 },
            { identifier = 'rangeMult', pin_id = 30, type = 4 }
        ] },
        { node_id = 7, output_pin = 14, position = { x = -76.0, y = 590.0 }, type = 'FloatNode', value = 0.0 },
        { node_id = 8, output_pin = 15, position = { x = 403.0, y = 402.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 16, type = 5 },
            { identifier = 'u_mode', pin_id = 17, type = 4 },
            { identifier = 'u_cat', pin_id = 18, type = 8 },
            { identifier = 'rangeMult', pin_id = 23, type = 4 }
        ] },
        { node_id = 9, output_pin = 19, position = { x = 705.0, y = 401.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 20, type = 5 },
            { identifier = 'u_mode', pin_id = 21, type = 4 },
            { identifier = 'u_cat', pin_id = 22, type = 8 },
            { identifier = 'rangeMult', pin_id = 24, type = 4 }
        ] },
        { node_id = 10, output_pin = 25, position = { x = 292.0, y = 168.00003051757812 }, type = 'FloatNode', value = 2.0 },
        { node_id = 11, output_pin = 26, position = { x = 232.0, y = 627.0 }, type = 'FloatNode', value = 0.0 },
        { node_id = 12, output_pin = 27, position = { x = -378.94253540039062, y = 582.55438232421875 }, type = 'FloatNode', value = 0.0 },
        { node_id = 13, output_pin = 28, position = { x = 532.0, y = 624.0 }, type = 'FloatNode', value = 1.0 },
        { node_id = 14, output_pin = 31, position = { x = -330.22662353515625, y = 171.86004638671875 }, type = 'FloatNode', value = 4.0 },
        { node_id = 15, output_pin = 32, position = { x = 1007.0, y = 399.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 33, type = 5 },
            { identifier = 'u_mode', pin_id = 34, type = 4 },
            { identifier = 'u_cat', pin_id = 35, type = 8 },
            { identifier = 'rangeMult', pin_id = 36, type = 4 }
        ] },
        { node_id = 16, output_pin = 37, position = { x = 1324.0, y = 399.0 }, shader_id = 1, type = 'FragmentShaderNode', uniform_pins = [
            { identifier = 'u_resolution', pin_id = 38, type = 5 },
            { identifier = 'u_mode', pin_id = 39, type = 4 },
            { identifier = 'u_cat', pin_id = 40, type = 8 },
            { identifier = 'rangeMult', pin_id = 41, type = 4 }
        ] },
        { node_id = 17, output_pin = 43, position = { x = 753.26025390625, y = 167.33135986328125 }, type = 'FloatNode', value = 1.0 },
        { node_id = 18, output_pin = 44, position = { x = 1043.080810546875, y = 618.4947509765625 }, type = 'FloatNode', value = 1.0 },
        { node_id = 19, output_pin = 45, position = { x = 790.559326171875, y = 618.223388671875 }, type = 'FloatNode', value = 0.0 }
    ]
    pins = [
        { node_id = 0, pin_id = 0, type = 8 },
        { node_id = 1, pin_id = 1, type = 4 },
        { node_id = 2, pin_id = 2, type = 5 },
        { node_id = 3, pin_id = 3, type = 8 },
        { node_id = 3, pin_id = 4, type = 5 },
        { node_id = 3, pin_id = 5, type = 4 },
        { node_id = 4, pin_id = 6, type = 4 },
        { node_id = 3, pin_id = 7, type = 4 },
        { node_id = 3, pin_id = 8, type = 8 },
        { node_id = 5, pin_id = 9, type = 8 },
        { node_id = 6, pin_id = 10, type = 8 },
        { node_id = 6, pin_id = 11, type = 5 },
        { node_id = 6, pin_id = 12, type = 4 },
        { node_id = 6, pin_id = 13, type = 8 },
        { node_id = 7, pin_id = 14, type = 4 },
        { node_id = 8, pin_id = 15, type = 8 },
        { node_id = 8, pin_id = 16, type = 5 },
        { node_id = 8, pin_id = 17, type = 4 },
        { node_id = 8, pin_id = 18, type = 8 },
        { node_id = 9, pin_id = 19, type = 8 },
        { node_id = 9, pin_id = 20, type = 5 },
        { node_id = 9, pin_id = 21, type = 4 },
        { node_id = 9, pin_id = 22, type = 8 },
        { node_id = 8, pin_id = 23, type = 4 },
        { node_id = 9, pin_id = 24, type = 4 },
        { node_id = 10, pin_id = 25, type = 4 },
        { node_id = 11, pin_id = 26, type = 4 },
        { node_id = 12, pin_id = 27, type = 4 },
        { node_id = 13, pin_id = 28, type = 4 },
        { node_id = 3, pin_id = 29, type = 4 },
        { node_id = 6, pin_id = 30, type = 4 },
        { node_id = 14, pin_id = 31, type = 4 },
        { node_id = 15, pin_id = 32, type = 8 },
        { node_id = 15, pin_id = 33, type = 5 },
        { node_id = 15, pin_id = 34, type = 4 },
        { node_id = 15, pin_id = 35, type = 8 },
        { node_id = 15, pin_id = 36, type = 4 },
        { node_id = 16, pin_id = 37, type = 8 },
        { node_id = 16, pin_id = 38, type = 5 },
        { node_id = 16, pin_id = 39, type = 4 },
        { node_id = 16, pin_id = 40, type = 8 },
        { node_id = 16, pin_id = 41, type = 4 },
        { node_id = 3, pin_id = 42, type = 8 },
        { node_id = 17, pin_id = 43, type = 4 },
        { node_id = 18, pin_id = 44, type = 4 },
        { node_id = 19, pin_id = 45, type = 4 }
    ]
    root_node = 0

    [[Assets.Shaders]]
    asset_id = 1
    name = 'Default'
    path = 'shaders/Default.glsl'

    [[Assets.Textures]]
    asset_id = 2
    name = 'Crisps-2787737411.jpg'
    path = '/home/zhangwei/Downloads/Crisps-2787737411.jpg'

[Settings]
current_workspace = 0
graph_id = 4
next_widget_id = 4

[[Workspaces]]
name = 'Shading'

    [[Workspaces.Widgets]]
    shader_id = 1
    type = 'EditorWidget'
    widget_id = 0

    [[Workspaces.Widgets]]
    graph_id = 4
    type = 'ViewportWidget'
    widget_id = 1

    [[Workspaces.Widgets]]
    type = 'ConsoleWidget'
    widget_id = 2

[[Workspaces]]
name = 'RenderGraph'

    [[Workspaces.Widgets]]
    graph_id = 4
    type = 'NodeEditorWidget'
    widget_id = 3
